// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: protocol/grpc/proto/grpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoomKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName     string `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	RoomChannel string `protobuf:"bytes,2,opt,name=roomChannel,proto3" json:"roomChannel,omitempty"`
}

func (x *GetRoomKeyRequest) Reset() {
	*x = GetRoomKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_grpc_proto_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomKeyRequest) ProtoMessage() {}

func (x *GetRoomKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_grpc_proto_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomKeyRequest.ProtoReflect.Descriptor instead.
func (*GetRoomKeyRequest) Descriptor() ([]byte, []int) {
	return file_protocol_grpc_proto_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoomKeyRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *GetRoomKeyRequest) GetRoomChannel() string {
	if x != nil {
		return x.RoomChannel
	}
	return ""
}

type GetRoomKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomKey string `protobuf:"bytes,1,opt,name=roomKey,proto3" json:"roomKey,omitempty"`
}

func (x *GetRoomKeyResponse) Reset() {
	*x = GetRoomKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_grpc_proto_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomKeyResponse) ProtoMessage() {}

func (x *GetRoomKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_grpc_proto_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomKeyResponse.ProtoReflect.Descriptor instead.
func (*GetRoomKeyResponse) Descriptor() ([]byte, []int) {
	return file_protocol_grpc_proto_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoomKeyResponse) GetRoomKey() string {
	if x != nil {
		return x.RoomKey
	}
	return ""
}

var File_protocol_grpc_proto_grpc_proto protoreflect.FileDescriptor

var file_protocol_grpc_proto_grpc_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x22, 0x4f, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x6f, 0x6f,
	0x6d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x2e, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x32, 0x5d, 0x0a, 0x10, 0x42,
	0x61, 0x63, 0x6b, 0x73, 0x74, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12,
	0x49, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x72, 0x76, 0x69, 0x6e, 0x36, 0x31,
	0x39, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_grpc_proto_grpc_proto_rawDescOnce sync.Once
	file_protocol_grpc_proto_grpc_proto_rawDescData = file_protocol_grpc_proto_grpc_proto_rawDesc
)

func file_protocol_grpc_proto_grpc_proto_rawDescGZIP() []byte {
	file_protocol_grpc_proto_grpc_proto_rawDescOnce.Do(func() {
		file_protocol_grpc_proto_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_grpc_proto_grpc_proto_rawDescData)
	})
	return file_protocol_grpc_proto_grpc_proto_rawDescData
}

var file_protocol_grpc_proto_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_grpc_proto_grpc_proto_goTypes = []interface{}{
	(*GetRoomKeyRequest)(nil),  // 0: grpc_api.GetRoomKeyRequest
	(*GetRoomKeyResponse)(nil), // 1: grpc_api.GetRoomKeyResponse
}
var file_protocol_grpc_proto_grpc_proto_depIdxs = []int32{
	0, // 0: grpc_api.BackstageManager.GetRoomKey:input_type -> grpc_api.GetRoomKeyRequest
	1, // 1: grpc_api.BackstageManager.GetRoomKey:output_type -> grpc_api.GetRoomKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_grpc_proto_grpc_proto_init() }
func file_protocol_grpc_proto_grpc_proto_init() {
	if File_protocol_grpc_proto_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_grpc_proto_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_grpc_proto_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_grpc_proto_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_grpc_proto_grpc_proto_goTypes,
		DependencyIndexes: file_protocol_grpc_proto_grpc_proto_depIdxs,
		MessageInfos:      file_protocol_grpc_proto_grpc_proto_msgTypes,
	}.Build()
	File_protocol_grpc_proto_grpc_proto = out.File
	file_protocol_grpc_proto_grpc_proto_rawDesc = nil
	file_protocol_grpc_proto_grpc_proto_goTypes = nil
	file_protocol_grpc_proto_grpc_proto_depIdxs = nil
}
